application: kijtra-twitprof
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /(.*\.(html|gif|png|jpg|ico|bmp|css|js|otf|eot|svg|ttf|woff))
  static_files: static/\1
  upload: static/(.*\.(html|gif|png|jpg|ico|bmp|css|js|otf|eot|svg|ttf|woff))

- url: /.*
  static_files: static/404.html
  upload: static/404.html